spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/file
  profiles:
    active: prod
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB
