spring:
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss:sss